### ISSUE TITLE
a bit confused about the difference between learning outcomes and objectives

### ISSUE THREAD

**Issue by wendwarge** [fibasile/fabacademyx-handbook#1]
have a crack at that while it's nighttime here.

**Comment by TheBeachLab** [comment]
Probably same thing but different wording. Please unify when Luciano reaches kiwiland

**Comment by fabulabu** [comment]
Yeah Im not a super expert but they way I have seen some people do it is to have the learning outcomes as a more general goal, such as:

"Student is capable of safely and efficiently using a laser cutter”

Within that you have the various objectives, or better yet, indicators, which basically are how you assess that the student has accomplished the learning outcome. So for the example these could be: 

Student is capable of identifying which materials can safely be used in the laser cutter
Student is able to create 2D vector drawings 
Student is able to use the correct PP for the laser cutter and set the correct values for the following parameters:
Speed
Power
Frequency
…
And so on..

Right? 

I’m sure its just a matter of terminology, I don't think I’m the one who put objectives, maybe Anna, but again it may have been me even though it’s not my preferred term. 

Is this clearer or more confusing now?

:P

Luc

**Comment by wendwarge** [comment]
Thanks Luciano, Anna wrote the eval check list which we used until 2015
without objectives or outcomes and then I wrote the learning outcomes with
Francisco for 2016. Ohad was questioning whether they should be called
objectives instead of outcomes, so I raised the issue for him to answer.
Partly to see how long it would take him to notice.
